aa=[30,20,10]
print("- 현재의 리스트 : %s" %aa)
aa.append(40)
print("- append 후의 리스트 : %s" %aa)
aa.pop()
print("- pop 후의 리스트 : %s" %aa)
aa.sort()
print("- sort 후의 리스트 : %s" %aa)
aa.reverse()
print("- reverse 후의 리스트 : %s" %aa)
aa.insert(2,222)
print("- insert 후의 리스트 : %s" %aa)
aa.remove(222)
print("- remove 후의 리스트 : %s" %aa)
aa.extend([77,77,77,88,55,77])
print("- extend 후의 리스트 : %s" %aa)
print("- 77값의 개수 : %d" %aa.count(77))